//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEcommerceEntities : DbContext
    {
        public dbEcommerceEntities()
            : base("name=dbEcommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tble_Cart> Tble_Cart { get; set; }
        public virtual DbSet<Tble_Category> Tble_Category { get; set; }
        public virtual DbSet<Tble_OrderDetails> Tble_OrderDetails { get; set; }
        public virtual DbSet<Tble_Orders> Tble_Orders { get; set; }
        public virtual DbSet<Tble_Product> Tble_Product { get; set; }
        public virtual DbSet<Tble_Roles> Tble_Roles { get; set; }
        public virtual DbSet<Tble_SlideImage> Tble_SlideImage { get; set; }
        public virtual DbSet<Tble_User> Tble_User { get; set; }
        public virtual DbSet<Tble_UserDetails> Tble_UserDetails { get; set; }
    }
}
